### ISSUE TITLE
Blog Config Structure

### ISSUE THREAD

**Issue by connorjburton** [BaunCMS/Framework#1]
So I am beginning to use this framework for my personal site and was mapping it all out in my head before diving into it.

I was thinking that the config could probably be separated for ease of use? To config/app.php and config/blog.php? Also what if I want two blogs, for example a "Journal" and a "Projects", maybe it should be renamed to listings instead, then in the listings.php config you can define an array of folders and configuration for each folder. Possibly even going to the length of /config/listings/x.php.

Just writing this out as a general discussion. I feel like Baun could be really good as a quick & simple turnaround framework but also feel that the blog config is out of place in config/app.php

**Comment by gilbitron** [comment]
I had the same thought about splitting up configs this morning. I think that's something I'll do soon.

I'm not sure about multiple blogs though. I don't think that will be a requirement for most people.
